services:
  nginx:
    build:
      context: . 
    ports:
      - "80:80"
    networks:
      - valheim-net
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
networks:
  valheim-net:
    external: true